/**
 * Design: 정밀한 식탁 — 기업 이야기는 선언보다 기준과 태도를 보여 주는 기록형 에디토리얼 구조로 다루며, 연혁·인증은 검증 가능한 신뢰 자산으로 배치한다.
 */
import { useState } from "react";
import { ArrowLeft, ArrowRight, ArrowUpRight, Award, Building2, CheckCircle2, MapPin, ShieldCheck } from "lucide-react";
import { FadeInSection } from "@/components/FadeInSection";
import { PageMeta } from "@/components/PageMeta";
import { SectionEyebrow } from "@/components/SectionEyebrow";
import { SubPageLayout } from "@/components/SubPageLayout";
import { barunfoodLocation } from "@/lib/location";

const principles = [["정직한 기준", "원재료부터 출고까지, 확인할 수 있는 기준을 우선합니다."], ["정밀한 공정", "반복되는 생산 안에서도 맛의 균일함을 고민합니다."], ["따뜻한 관계", "필요한 조건을 듣고 가능한 방법부터 함께 살핍니다."]];
const timeline = [["2008", "RESEARCH", "도우 연구소 개설", "도우의 맛과 가치를 연구하기 위한 기반을 마련했습니다."], ["2009", "MANUFACTURING", "피자 도우 부천 공장 생산 사업 시작", "피자 도우 생산 사업을 시작하며 제조 기반을 확장했습니다."], ["2010", "FACILITY", "부평공장 이전 · 시흥 제1공장 완공", "생산 환경을 정비하고 시흥 제1공장을 완공했습니다."], ["2011", "FACILITY", "시흥 제2공장 완공", "증가하는 생산 수요에 맞춰 시흥 제2공장을 완공했습니다."], ["2012", "FACILITY", "시흥 제3공장 완공", "시흥 제3공장을 완공하며 제조 기반을 넓혔습니다."], ["2014", "EXPORT", "중국·홍콩지사 도우믹스 수출", "해외 외식업체 중국지사와 홍콩지사에 도우믹스를 수출했습니다."], ["2015", "PRODUCT & EXPORT", "맞춤 도우 개발 · 미국지사 도우믹스 수출", "(주)새아침 납품용 공식 피자 도우와 흑미 도우를 개발하고, 해외 외식업체 미국지사에 도우믹스를 수출한 기록이 공개돼 있습니다."], ["2016", "QUALITY & FACILITY", "HACCP 인증 획득 · 검단 신공장 이전", "HACCP 인증을 획득하고 인천 검단 오류동 신공장으로 이전한 기록이 공개돼 있습니다."], ["2017", "PRODUCT & EXPORT", "화덕·흑미 라떼 도우 개발 · 싱가포르 수출", "화덕 도우와 흑미 라떼 도우 개발, 해외 외식업체 싱가포르지사 도우믹스 수출 기록이 공개돼 있습니다."], ["2018", "PRODUCT DEVELOPMENT", "피자 3종 · 플랫 피자 개발", "GN 푸드 피자 3종과 고르곤졸라 밀크 플랫 피자 개발 기록이 공개돼 있습니다."], ["2020", "PRODUCT & IP", "도우 개발 · 피자 제공 방법 특허 · 크로플", "오징어 먹물 플랫 도우와 프리미엄 라떼 도우를 개발하고, 피자의 제공 방법 특허를 획득했으며 크로플 개발 기록이 공개돼 있습니다."], ["2021", "IP & PRODUCT", "도우 성형 장치 특허 · 벤처기업 인증", "피자도우 성형 장치 특허와 벤처기업 인증 획득, 페파로니 피자 개발 기록이 공개돼 있습니다."]];
const certifications = [
  { code: "01", label: "FOOD SAFETY", title: "HACCP", text: "현행 바른푸드 메인 화면에서 ‘HACCP 인증 획득’으로 공개한 식품안전 관리 항목입니다.", evidence: "SOURCE / CURRENT MAIN PAGE", detail: "공개 전 확인: 발급기관 · 적용 공정 · 유효기간", icon: ShieldCheck },
  { code: "02", label: "INTELLECTUAL PROPERTY", title: "피자도우 성형 장치 특허", text: "현행 공개 연혁에는 피자도우 성형 장치 특허 획득 이력이 표기되어 있습니다.", evidence: "SOURCE / PUBLIC HISTORY", detail: "공개 전 확인: 특허번호 · 등록일 · 적용 범위", icon: Award },
  { code: "03", label: "RESEARCH INFRASTRUCTURE", title: "기업부설연구소", text: "현행 사업소개 메뉴에 기업부설연구소를 연구개발 역량으로 소개하고 있습니다.", evidence: "SOURCE / BUSINESS MENU", detail: "공개 전 확인: 연구 분야 · 운영 현황 · 조직 정보", icon: Building2 },
  { code: "04", label: "MANUFACTURING RECORD", title: "시흥 생산 기반", text: "공개 연혁에는 2010년부터 2012년까지 시흥 제1·2·3공장 완공 이력이 기록되어 있습니다.", evidence: "SOURCE / 2010–2012 HISTORY", detail: "공개 전 확인: 현재 운영 시설 · 적용 제품군", icon: CheckCircle2 },
];

export default function Company() {
  const [activeCertification, setActiveCertification] = useState(0);
  const current = certifications[activeCertification];
  const CurrentIcon = current.icon;
  const nextCertification = () => setActiveCertification((index) => (index + 1) % certifications.length);
  const previousCertification = () => setActiveCertification((index) => (index - 1 + certifications.length) % certifications.length);

  return (
    <SubPageLayout marker="01" eyebrow="COMPANY ARCHIVE" heroVariant="company" title={<>기준은 말보다,<br /><span className="text-[#9e3328]">남겨진 기록으로 보입니다.</span></>} description="바른푸드는 도우와 피자를 만드는 식품 제조기업입니다. 연구의 시작부터 생산 기반의 확장까지, 반복되는 맛을 위한 기록을 쌓아 왔습니다.">
      <PageMeta title="회사소개 | 바른푸드 기업 아카이브" description="연구와 제조 기반, 공개 가능한 신뢰 기록을 바탕으로 반복되는 맛의 기준을 쌓아 온 바른푸드의 기업 아카이브입니다." path="/company" image="/manus-storage/barunfood-company-og-image_2bf6582a.jpg" imageAlt="바른푸드 회사소개 — 남겨진 기록으로 보는 기준" />
      <FadeInSection className="bg-[#f7f3eb] px-5 py-20 sm:px-8 sm:py-28 lg:px-12 lg:py-36"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:gap-20"><div><SectionEyebrow number="02">OPERATING PRINCIPLES</SectionEyebrow><p className="mt-8 max-w-sm text-[15px] leading-7 text-[#70685d]">기업의 기준은 선언이 아니라 운영 방식으로 남아야 합니다. 바른푸드는 제품, 공정, 협업에서 확인할 수 있는 기준을 쌓아 갑니다.</p></div><div id="approach"><h2 className="font-serif text-[clamp(2.4rem,4.6vw,4.9rem)] font-semibold leading-[1.04] tracking-[-0.08em]">기업의 기준은,<span className="block">운영의 기록으로 남습니다.</span></h2><div className="mt-12 divide-y divide-[#d9d0c2] border-y border-[#d9d0c2]">{principles.map(([title, text], index) => <article key={title} className="grid grid-cols-[44px_1fr] gap-5 py-6 sm:grid-cols-[78px_1fr] sm:py-8"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#9e3328] text-[10px] font-bold text-white">0{index + 1}</span><div><h3 className="text-xl font-bold tracking-[-0.05em]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#70685d]">{text}</p></div></article>)}</div></div></div></FadeInSection>
      <FadeInSection className="bg-[#ece5d9] px-5 py-20 sm:px-8 sm:py-28 lg:px-12 lg:py-36"><div className="mx-auto max-w-[1440px]"><div className="grid gap-8 lg:grid-cols-[0.78fr_1.22fr]"><div><SectionEyebrow number="03">OUR TIMELINE</SectionEyebrow><h2 className="mt-8 font-serif text-[clamp(2.35rem,4.3vw,4.8rem)] font-semibold leading-[1.04] tracking-[-0.08em]">시간이 쌓일수록,<br />기준은 더 선명해집니다.</h2><p className="mt-7 max-w-sm text-sm leading-6 text-[#70685d]">공식 공개 연혁의 2008년부터 2021년까지 주요 기록을 바탕으로 구성했습니다. 인증·특허의 현재 적용 범위와 유효 상태는 실제 증빙으로 별도 확인해야 합니다.</p><div className="ingredient-window mt-9 h-48 max-w-sm overflow-hidden rounded-br-[72px]"><img src="/assets/barun-dough-research-review.jpg" alt="도우 연구를 검토하는 현장" className="h-full w-full object-cover" /><span className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 to-transparent px-4 pb-4 pt-10 text-[10px] font-bold tracking-[0.14em] text-white/85">ARCHIVE VIEW / DOUGH R&D</span></div></div><div className="relative border-l border-[#c5baa9] pl-8 sm:pl-14">{timeline.map(([year, label, title, text]) => <article key={year} className="relative pb-10 last:pb-0"><span className="absolute -left-[49px] top-0 grid h-10 w-10 place-items-center rounded-full border border-[#9e3328] bg-[#ece5d9] text-[10px] font-bold text-[#9e3328] sm:-left-[77px]">{year}</span><p className="text-[10px] font-bold tracking-[0.16em] text-[#9e3328]">{label}</p><div className="mt-3 flex flex-col justify-between gap-3 border-b border-[#cfc5b5] pb-7 sm:flex-row"><div><h3 className="text-xl font-bold tracking-[-0.05em]">{title}</h3><p className="mt-2 max-w-md text-sm leading-6 text-[#70685d]">{text}</p></div><span className="shrink-0 text-[10px] font-bold tracking-[0.14em] text-[#8b8174]">YEAR / {year}</span></div></article>)}</div></div></div></FadeInSection>
      <FadeInSection className="bg-[#242321] px-5 py-20 text-white sm:px-8 sm:py-28 lg:px-12 lg:py-36"><div className="mx-auto max-w-[1440px]"><div className="grid gap-8 lg:grid-cols-[0.76fr_1.24fr]"><div><SectionEyebrow number="04" light>CERTIFICATION & RECORDS</SectionEyebrow><h2 className="mt-8 font-serif text-[clamp(2.35rem,4.5vw,4.9rem)] font-semibold leading-[1.04] tracking-[-0.08em]">신뢰는 마크가 아니라,<br /><span className="text-[#f4bd75]">확인 가능한 기록입니다.</span></h2><p className="mt-7 max-w-sm text-sm leading-6 text-white/60">각 항목은 현행 공개 페이지에서 확인한 정보입니다. 인증·특허의 발급기관, 적용 범위, 유효기간은 실제 증빙을 검토한 뒤 공개해야 합니다.</p></div><div className="relative overflow-hidden border border-white/20 bg-white/[0.03] p-7 sm:p-10"><span className="absolute right-[-28px] top-[-28px] grid h-36 w-36 place-items-center rounded-full border-[18px] border-[#9e3328]/25 font-serif text-3xl text-white/20">{current.code}</span><div className="relative"><div className="flex items-center justify-between"><span className="grid h-12 w-12 place-items-center rounded-full bg-[#9e3328] text-white"><CurrentIcon className="h-6 w-6" /></span><p className="text-[10px] font-bold tracking-[0.16em] text-[#f4bd75]">CERTIFICATION FILE / {current.code}</p></div><p className="mt-14 text-[10px] font-bold tracking-[0.18em] text-[#f4bd75]">{current.label}</p><h3 className="mt-3 font-serif text-4xl font-semibold tracking-[-0.07em]">{current.title}</h3><p className="mt-5 max-w-xl text-sm leading-7 text-white/65">{current.text}</p><div className="mt-7 grid gap-3 border-y border-white/15 py-4 text-[10px] sm:grid-cols-[128px_1fr]"><span className="font-bold tracking-[0.14em] text-white/45">PUBLIC EVIDENCE</span><span className="font-bold tracking-[0.08em] text-[#f4bd75]">{current.evidence}</span><span className="font-bold tracking-[0.14em] text-white/45">DETAIL TO VERIFY</span><span className="leading-5 text-white/70">{current.detail}</span></div><div className="mt-7 flex items-center justify-between"><div className="flex gap-2">{certifications.map((item, index) => <button type="button" key={item.code} onClick={() => setActiveCertification(index)} aria-label={`${item.title} 보기`} aria-pressed={index === activeCertification} className={`h-2 w-8 transition ${index === activeCertification ? "bg-[#9e3328]" : "bg-white/20 hover:bg-white/50"}`} />)}</div><div className="flex gap-2"><button type="button" onClick={previousCertification} aria-label="이전 인증 보기" className="grid h-9 w-9 place-items-center border border-white/25 transition hover:border-[#9e3328] hover:bg-[#9e3328]"><ArrowLeft className="h-4 w-4" /></button><button type="button" onClick={nextCertification} aria-label="다음 인증 보기" className="grid h-9 w-9 place-items-center border border-white/25 transition hover:border-[#9e3328] hover:bg-[#9e3328]"><ArrowRight className="h-4 w-4" /></button></div></div></div></div></div></div></FadeInSection>
      <FadeInSection className="bg-[#242321] px-5 pb-20 text-white sm:px-8 sm:pb-28 lg:px-12 lg:pb-32"><div className="mx-auto grid max-w-[1440px] gap-10 border-t border-white/20 pt-16 lg:grid-cols-[0.8fr_1.2fr]"><SectionEyebrow number="05" light>SUPPLY RESPONSIBILITY</SectionEyebrow><div><h2 className="font-serif text-[clamp(2.4rem,4.7vw,5rem)] font-semibold leading-[1.03] tracking-[-0.08em]">공개 가능한 기록으로,<br /><span className="text-[#f4bd75]">공급의 책임을 관리합니다.</span></h2><p className="mt-7 max-w-xl text-[15px] leading-7 text-white/65">연혁, 인증, 제조 기반은 기업의 신뢰를 확인하는 출발점입니다. 공정과 품질의 구체 기준은 제조·R&D 페이지에서 더 자세히 확인할 수 있습니다.</p><a href="/manufacturing#quality" className="mt-8 inline-flex items-center gap-2 border-b border-white/50 pb-2 text-sm font-bold transition hover:border-[#9e3328] hover:text-[#f4bd75]">제조·품질 기준 보기 <ArrowUpRight className="h-4 w-4" /></a></div></div></FadeInSection>
      <FadeInSection id="contact" className="bg-[#ece5d9] px-5 py-20 sm:px-8 sm:py-28 lg:px-12"><div className="mx-auto grid max-w-[1440px] gap-8 lg:grid-cols-[0.9fr_1.1fr]"><div><SectionEyebrow number="06">CONTACT & LOCATION</SectionEyebrow><h2 className="mt-8 font-serif text-[clamp(2.4rem,4vw,4.5rem)] font-semibold tracking-[-0.08em]">바른푸드의 기록이<br />궁금하신가요?</h2></div><div className="border-t border-[#cfc5b5]"><div className="grid gap-4 border-b border-[#cfc5b5] py-7 sm:grid-cols-[130px_1fr]"><span className="text-[10px] font-bold tracking-[0.18em] text-[#9e3328]">ADDRESS</span><p className="text-[15px] leading-7">{barunfoodLocation.address}</p></div><div className="grid gap-4 border-b border-[#cfc5b5] py-7 sm:grid-cols-[130px_1fr]"><span className="text-[10px] font-bold tracking-[0.18em] text-[#9e3328]">CONTACT</span><p className="text-[15px] leading-7">T. {barunfoodLocation.phone}<br />E. {barunfoodLocation.email}</p></div><a href={barunfoodLocation.path} className="group mt-8 inline-flex items-center gap-3 border-b border-[#242321] pb-2 text-sm font-bold">오시는 길 상세 보기 <MapPin className="h-4 w-4 text-[#9e3328]" /><ArrowUpRight className="h-4 w-4 transition group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></a></div></div></FadeInSection>
    </SubPageLayout>
  );
}
