import { ArrowUpRight, CircleGauge, PackageCheck, Ruler, Wheat } from "lucide-react";
import { FadeInSection } from "@/components/FadeInSection";
import { PageMeta } from "@/components/PageMeta";
import { SectionEyebrow } from "@/components/SectionEyebrow";
import { SubPageLayout } from "@/components/SubPageLayout";

const doughViews = [
  ["STORAGE", "보관 조건", "제품의 보관·해동 조건은 실제 라벨과 최신 규격서를 기준으로 확인합니다.", "/assets/dough-type-frozen.webp", PackageCheck],
  ["FORM", "기본 형태", "메뉴와 조리 방식에 맞춰 필요한 도우의 형태와 사용 조건을 검토합니다.", "/assets/dough-type-standard.webp", Wheat],
  ["THICKNESS", "얇은 타입", "얇은 도우의 조리 결과는 설비·온도·시간에 따라 달라질 수 있어 현장 조건을 함께 봅니다.", "/assets/dough-type-thin.webp", Ruler],
  ["VOLUME", "볼륨 지향", "식감과 볼륨을 원하는 메뉴에는 반죽의 상태와 조리 환경을 함께 검토합니다.", "/assets/dough-type-volume.webp", CircleGauge],
] as const;

export default function DoughCollection() {
  return <SubPageLayout marker="03" eyebrow="DOUGH COLLECTION" breadcrumbLabel="바른 도우" heroVariant="products" heroImage="/assets/home-thick-soft-dough.webp" heroImageAlt="도우의 결을 보여 주는 바른푸드 제품 이미지" title={<>도우는 한 가지 형태가 아니라,<br /><span className="text-[#9e3328]">메뉴를 받치는 조건입니다.</span></>} description="보관, 두께, 식감, 사용 환경을 함께 읽고 메뉴의 시작을 받치는 도우 제품군을 검토합니다.">
    <PageMeta title="바른 도우 | 바른푸드 도우 제품" description="보관·두께·식감·사용 환경을 기준으로 메뉴에 맞는 도우 제품군을 검토하는 바른푸드 바른 도우 페이지입니다." path="/products/dough" image="/manus-storage/barunfood-product-og-image_272ba6cb.jpg" imageAlt="바른 도우 — 메뉴를 받치는 조건" />
    <FadeInSection className="bg-[#ece5d9] px-5 py-20 sm:px-8 sm:py-28 lg:px-12 lg:py-36"><div className="mx-auto max-w-[1440px]"><div className="grid gap-10 lg:grid-cols-[0.76fr_1.24fr] lg:items-end"><div><SectionEyebrow number="04">DOUGH CONDITIONS</SectionEyebrow><p className="mt-8 max-w-sm text-sm leading-7 text-[#70685d]">이미지는 도우 사용 조건을 생각하기 위한 안내입니다. 실제 제품 구분·규격·보관 기준은 제품 파일과 최신 라벨을 기준으로 확인해야 합니다.</p></div><h2 className="font-serif text-[clamp(2.4rem,4.6vw,5rem)] font-semibold leading-[1.03] tracking-[-0.08em]">필요한 식감은,<br /><span className="text-[#9e3328]">조건에서 먼저 찾습니다.</span></h2></div><div className="mt-14 grid gap-5 sm:grid-cols-2 lg:mt-20 lg:grid-cols-4">{doughViews.map(([label, title, text, image, Icon], index) => <article key={label} className="overflow-hidden bg-[#242321] text-white"><div className="relative aspect-square overflow-hidden"><img src={image} alt={`${title} 도우 상태 예시`} className="h-full w-full object-cover transition duration-700 hover:scale-[1.04]" /><span className="absolute left-4 top-4 grid h-8 w-8 place-items-center rounded-full bg-[#9e3328] text-[10px] font-bold">0{index + 1}</span></div><div className="p-6"><div className="flex items-center justify-between"><span className="text-[10px] font-bold tracking-[0.16em] text-[#f4bd75]">{label}</span><Icon className="h-4 w-4 text-[#f4bd75]" /></div><h3 className="mt-5 text-xl font-bold tracking-[-0.05em]">{title}</h3><p className="mt-3 text-sm leading-6 text-white/65">{text}</p></div></article>)}</div></div></FadeInSection>
    <FadeInSection className="bg-[#f7f3eb] px-5 py-20 sm:px-8 sm:py-28 lg:px-12 lg:py-36"><div className="mx-auto grid max-w-[1440px] gap-10 lg:grid-cols-[0.72fr_1.28fr]"><div><SectionEyebrow number="05">DOUGH FILES</SectionEyebrow><h2 className="mt-8 font-serif text-[clamp(2.3rem,4.2vw,4.6rem)] font-semibold leading-[1.04] tracking-[-0.08em]">제품 파일로 먼저,<br />사용 조건을 확인하세요.</h2></div><div className="grid border-y border-[#d9d0c2] md:grid-cols-2"><a href="/products?product=dough" className="group border-b border-[#d9d0c2] py-8 md:border-b-0 md:border-r md:pr-8"><div className="flex items-center justify-between"><span className="text-[10px] font-bold tracking-[0.16em] text-[#9e3328]">DOUGH / FILE 03</span><Wheat className="h-5 w-5 text-[#9e3328]" /></div><h3 className="mt-12 text-2xl font-bold tracking-[-0.06em]">바른 도우</h3><p className="mt-3 text-sm leading-6 text-[#70685d]">메뉴의 시작을 받치는 피자 도우 솔루션입니다. 반죽 규격과 사용 조건은 제품 파일에서 확인합니다.</p><span className="mt-8 inline-flex items-center gap-2 text-sm font-bold group-hover:text-[#9e3328]">제품 파일 열기 <ArrowUpRight className="h-4 w-4" /></span></a><a href="/products?product=foodservice" className="group py-8 md:pl-8"><div className="flex items-center justify-between"><span className="text-[10px] font-bold tracking-[0.16em] text-[#9e3328]">DOUGH / FILE 04</span><PackageCheck className="h-5 w-5 text-[#9e3328]" /></div><h3 className="mt-12 text-2xl font-bold tracking-[-0.06em]">푸드서비스 도우</h3><p className="mt-3 text-sm leading-6 text-[#70685d]">운영 조건과 납품 단위를 함께 검토한 뒤 필요한 규격을 안내하는 도우 제품군입니다.</p><span className="mt-8 inline-flex items-center gap-2 text-sm font-bold group-hover:text-[#9e3328]">제품 파일 열기 <ArrowUpRight className="h-4 w-4" /></span></a></div></div></FadeInSection>
    <FadeInSection className="bg-[#242321] px-5 py-16 text-white sm:px-8 lg:px-12 lg:py-20"><div className="mx-auto flex max-w-[1440px] flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><SectionEyebrow number="06" light>DOUGH CONSULTATION</SectionEyebrow><h2 className="mt-7 font-serif text-[clamp(2.3rem,4.4vw,4.7rem)] font-semibold leading-[1.03] tracking-[-0.08em]">메뉴의 시작 조건을<br /><span className="text-[#f4bd75]">함께 검토해 보세요.</span></h2></div><a href="/partnership" className="consultation-cta inline-flex items-center justify-center gap-3 bg-[#9e3328] px-6 py-4 text-sm font-bold text-white hover:bg-white hover:text-[#9e3328]">도우 제품 상담 <ArrowUpRight className="cta-arrow h-4 w-4" /></a></div></FadeInSection>
  </SubPageLayout>;
}
