import { ArrowUpRight, ChefHat, Flame, Pizza, Store } from "lucide-react";
import { FadeInSection } from "@/components/FadeInSection";
import { PageMeta } from "@/components/PageMeta";
import { SectionEyebrow } from "@/components/SectionEyebrow";
import { SubPageLayout } from "@/components/SubPageLayout";

const menuStudies = [
  ["TOMATO & CHEESE", "토마토·치즈 조합", "도우의 형태와 토핑 밸런스를 함께 보는 메뉴 응용 예시입니다.", "/assets/hero-pizza-margherita.webp"],
  ["MUSHROOM", "버섯 토핑 조합", "재료의 수분감과 조리 환경을 고려해 메뉴 구성을 검토하는 예시입니다.", "/assets/hero-pizza-bulgogi.webp"],
  ["PEPPERONI", "페퍼로니 조합", "열과 시간에 따른 치즈·토핑의 변화를 함께 살피는 메뉴 응용 예시입니다.", "/assets/hero-pizza-pepperoni.webp"],
] as const;

export default function PizzaCollection() {
  return <SubPageLayout marker="03" eyebrow="PIZZA COLLECTION" breadcrumbLabel="요리 담은 피자" heroVariant="products" heroImage="/assets/real-detroit-pizza-background.jpg" heroImageAlt="토마토와 치즈를 올린 피자 메뉴 응용 예시" title={<>피자는 토핑보다 먼저,<br /><span className="text-[#9e3328]">도우의 조건을 읽습니다.</span></>} description="메뉴 의도, 조리 설비, 운영 흐름을 함께 보고 피자 제품군과 도우의 사용 조건을 검토합니다.">
    <PageMeta title="요리 담은 피자 | 바른푸드 제품 응용" description="메뉴 의도와 조리 환경을 함께 읽고 피자 제품군·도우의 사용 조건을 검토하는 바른푸드 피자 응용 페이지입니다." path="/products/pizza" image="/assets/real-detroit-pizza-background.jpg" imageAlt="바른푸드 요리 담은 피자 — 메뉴 응용 기록" />
    <FadeInSection className="bg-[#242321] px-5 py-20 text-white sm:px-8 sm:py-28 lg:px-12 lg:py-36"><div className="mx-auto max-w-[1440px]"><div className="grid gap-10 lg:grid-cols-[0.76fr_1.24fr] lg:items-end"><div><SectionEyebrow number="04" light>MENU APPLICATION</SectionEyebrow><p className="mt-8 max-w-sm text-sm leading-7 text-white/65">아래 이미지는 메뉴 응용의 방향을 보여 주는 예시입니다. 실제 판매 SKU·규격·알레르기 정보는 제품 파일과 최신 라벨을 기준으로 확인해야 합니다.</p></div><h2 className="font-serif text-[clamp(2.4rem,4.6vw,5rem)] font-semibold leading-[1.03] tracking-[-0.08em]">한 조각의 메뉴도,<br /><span className="text-[#f4bd75]">사용 환경에서 설계합니다.</span></h2></div><div className="mt-14 grid gap-5 md:grid-cols-3 lg:mt-20">{menuStudies.map(([label, title, text, image], index) => <article key={label} className="group relative min-h-[430px] overflow-hidden border border-white/15"><img src={image} alt={`${title} 피자 메뉴 응용 예시`} className="absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-[1.04]" /><div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/15 to-black/10" /><div className="absolute inset-x-0 top-0 flex items-center justify-between border-b border-white/20 px-5 py-4 text-[10px] font-bold tracking-[0.15em] text-white/80"><span>STUDY / 0{index + 1}</span><span>{label}</span></div><div className="absolute inset-x-0 bottom-0 p-7"><Pizza className="h-5 w-5 text-[#f4bd75]" /><h3 className="mt-7 text-2xl font-bold tracking-[-0.06em]">{title}</h3><p className="mt-3 text-sm leading-6 text-white/70">{text}</p></div></article>)}</div></div></FadeInSection>
    <FadeInSection className="bg-[#f7f3eb] px-5 py-20 sm:px-8 sm:py-28 lg:px-12 lg:py-36"><div className="mx-auto grid max-w-[1440px] gap-10 lg:grid-cols-[0.72fr_1.28fr]"><div><SectionEyebrow number="05">PRODUCT FILES</SectionEyebrow><h2 className="mt-8 font-serif text-[clamp(2.3rem,4.2vw,4.6rem)] font-semibold leading-[1.04] tracking-[-0.08em]">필요한 피자 제품은,<br />파일에서 확인합니다.</h2></div><div className="grid border-y border-[#d9d0c2] md:grid-cols-2"><a href="/products?product=detroit" className="group border-b border-[#d9d0c2] py-8 md:border-b-0 md:border-r md:pr-8"><div className="flex items-center justify-between"><span className="text-[10px] font-bold tracking-[0.16em] text-[#9e3328]">PIZZA / FILE 01</span><ChefHat className="h-5 w-5 text-[#9e3328]" /></div><h3 className="mt-12 text-2xl font-bold tracking-[-0.06em]">리얼 디트로이트 피자</h3><p className="mt-3 text-sm leading-6 text-[#70685d]">두툼한 도우와 치즈의 식감을 담은 네모 피자 라인입니다. 제품 규격은 파일에서 확인하세요.</p><span className="mt-8 inline-flex items-center gap-2 text-sm font-bold group-hover:text-[#9e3328]">제품 파일 열기 <ArrowUpRight className="h-4 w-4" /></span></a><a href="/products?product=thin" className="group py-8 md:pl-8"><div className="flex items-center justify-between"><span className="text-[10px] font-bold tracking-[0.16em] text-[#9e3328]">PIZZA / FILE 02</span><Flame className="h-5 w-5 text-[#9e3328]" /></div><h3 className="mt-12 text-2xl font-bold tracking-[-0.06em]">씬 피자</h3><p className="mt-3 text-sm leading-6 text-[#70685d]">바삭한 식감의 피자 라인입니다. 매장 오븐과 조리 환경에 맞는 조건은 상담으로 확인합니다.</p><span className="mt-8 inline-flex items-center gap-2 text-sm font-bold group-hover:text-[#9e3328]">제품 파일 열기 <ArrowUpRight className="h-4 w-4" /></span></a></div></div></FadeInSection>
    <FadeInSection className="bg-[#9e3328] px-5 py-16 text-white sm:px-8 lg:px-12 lg:py-20"><div className="mx-auto flex max-w-[1440px] flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><SectionEyebrow number="06" light>MENU CONSULTATION</SectionEyebrow><h2 className="mt-7 font-serif text-[clamp(2.3rem,4.4vw,4.7rem)] font-semibold leading-[1.03] tracking-[-0.08em]">메뉴와 조리 조건을<br />함께 검토해 보세요.</h2></div><a href="/partnership#inquiry" className="consultation-cta inline-flex items-center justify-center gap-3 bg-white px-6 py-4 text-sm font-bold text-[#9e3328] hover:bg-[#242321] hover:text-white"><Store className="h-4 w-4" />피자 제품 상담 <ArrowUpRight className="cta-arrow h-4 w-4" /></a></div></FadeInSection>
  </SubPageLayout>;
}
