import { ArrowUpRight, ClipboardCheck, PackageCheck, Refrigerator, ShieldCheck } from "lucide-react";
import { FadeInSection } from "@/components/FadeInSection";
import { PageMeta } from "@/components/PageMeta";
import { SectionEyebrow } from "@/components/SectionEyebrow";
import { SubPageLayout } from "@/components/SubPageLayout";

const checkpoints = [
  ["01", "BRIEF CHECK", "사용 환경을 먼저 정리합니다.", "매장 오븐, 보관 방식, 메뉴 목적처럼 품질에 영향을 주는 정보를 먼저 확인합니다.", ClipboardCheck],
  ["02", "PROCESS REVIEW", "반죽부터 포장까지 연결합니다.", "반죽·성형·가열·포장 단계마다 제품 규격과 공정 흐름의 연결을 살핍니다.", ShieldCheck],
  ["03", "RELEASE REVIEW", "출고 전 제품 상태를 남깁니다.", "출고 전 제품 상태, 포장, 라벨 정보를 기준으로 필요한 항목을 확인합니다.", PackageCheck],
  ["04", "STORAGE CONTEXT", "보관·해동·조리까지 안내합니다.", "현장 설비와 제품 라벨을 바탕으로 보관, 해동, 조리 방법을 함께 정리합니다.", Refrigerator],
] as const;

export default function QualitySafety() {
  return <SubPageLayout marker="02" eyebrow="QUALITY & SAFETY" breadcrumbLabel="품질·안전" heroVariant="manufacturing" heroImage="/assets/real-quality-line-rnd-hq.webp" heroImageAlt="제조 라인에서 제품 상태를 확인하는 바른푸드 현장" title={<>안전은 마지막 확인이 아니라,<br /><span className="text-[#9e3328]">공정 전체의 기준입니다.</span></>} description="매장 사용 환경부터 반죽·성형·포장·출고·보관까지 연결해 제품 상태를 안정적으로 관리합니다.">
    <PageMeta title="품질·안전 | 바른푸드 제조 기준" description="매장 사용 환경부터 반죽·성형·포장·출고·보관까지 연결해 관리하는 바른푸드 품질·안전 페이지입니다." path="/manufacturing/quality" image="/manus-storage/barunfood-company-og-image_2bf6582a.jpg" imageAlt="바른푸드 품질·안전 — 공정 전체의 기준" />
    <FadeInSection className="bg-[#242321] px-5 py-20 text-white sm:px-8 sm:py-28 lg:px-12 lg:py-36"><div className="mx-auto max-w-[1440px]"><div className="grid gap-8 lg:grid-cols-[0.72fr_1.28fr] lg:items-end"><div><SectionEyebrow number="03" light>CHECKPOINT MAP</SectionEyebrow><p className="mt-8 max-w-sm text-sm leading-7 text-white/65">품질은 완제품만 보는 일이 아니라, 반죽부터 매장 사용까지 이어지는 흐름을 관리하는 일입니다.</p></div><h2 className="font-serif text-[clamp(2.4rem,4.6vw,5rem)] font-semibold leading-[1.03] tracking-[-0.08em]">품질 관리는,<br /><span className="text-[#f4bd75]">공정마다 이어집니다.</span></h2></div><div className="mt-14 grid border-y border-white/20 md:grid-cols-2 lg:mt-20 lg:grid-cols-4">{checkpoints.map(([number, label, title, text, Icon]) => <article key={label} className="border-b border-white/15 p-7 last:border-b-0 md:border-b-0 md:border-r md:even:border-r-0 lg:even:border-r lg:last:border-r-0"><div className="flex items-center justify-between"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#9e3328] text-[10px] font-bold">{number}</span><Icon className="h-5 w-5 text-[#f4bd75]" /></div><p className="mt-11 text-[10px] font-bold tracking-[0.16em] text-[#f4bd75]">{label}</p><h3 className="mt-3 text-lg font-bold tracking-[-0.04em]">{title}</h3><p className="mt-3 text-sm leading-6 text-white/60">{text}</p></article>)}</div></div></FadeInSection>
    <FadeInSection className="bg-[#f7f3eb] px-5 py-20 sm:px-8 sm:py-28 lg:px-12 lg:py-36"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[0.72fr_0.58fr_0.7fr]"><div><SectionEyebrow number="04">PUBLIC RECORD</SectionEyebrow><h2 className="mt-8 font-serif text-[clamp(2.3rem,4.4vw,4.7rem)] font-semibold leading-[1.04] tracking-[-0.08em]">공개 기록과<br />현재 확인을 구분합니다.</h2></div><div className="border-y border-[#d9d0c2] py-7 lg:border-l lg:border-y-0 lg:px-9"><p className="text-[10px] font-bold tracking-[0.16em] text-[#9e3328]">2016 / PUBLIC HISTORY</p><h3 className="mt-4 text-xl font-bold tracking-[-0.05em]">HACCP 인증 획득 기록</h3><p className="mt-4 text-sm leading-7 text-[#70685d]">공식 공개 연혁에는 2016년 HACCP 인증 획득 기록이 남아 있습니다. 적용 공정, 발급기관, 유효기간은 상담 시 실제 증빙 기준으로 안내합니다.</p></div><div className="rounded-bl-[72px] bg-[#ece5d9] p-8"><p className="text-[10px] font-bold tracking-[0.16em] text-[#9e3328]">REQUEST FILE</p><h3 className="mt-4 text-xl font-bold tracking-[-0.05em]">필요한 품질 자료를 알려주세요.</h3><p className="mt-4 text-sm leading-7 text-[#70685d]">제품군, 매장 사용 환경, 필요한 품질 자료를 남겨주시면 담당자가 다음 정보를 안내합니다.</p><a href="/partnership" className="consultation-cta mt-8 inline-flex items-center gap-2 border-b border-[#242321] pb-2 text-sm font-bold hover:border-[#9e3328] hover:text-[#9e3328]">품질·안전 기준 문의 <ArrowUpRight className="cta-arrow h-4 w-4" /></a></div></div></FadeInSection>
  </SubPageLayout>;
}
