import { ArrowUpRight, ClipboardCheck, PackageCheck, Refrigerator, ShieldCheck } from "lucide-react";
import { FadeInSection } from "@/components/FadeInSection";
import { PageMeta } from "@/components/PageMeta";
import { SectionEyebrow } from "@/components/SectionEyebrow";
import { SubPageLayout } from "@/components/SubPageLayout";

const checkpoints = [
  ["01", "BRIEF CHECK", "제품의 사용 환경부터 확인합니다.", "메뉴 목적, 원재료 조건, 보관과 조리 환경처럼 이후 기준을 바꾸는 정보를 먼저 검토합니다.", ClipboardCheck],
  ["02", "PROCESS REVIEW", "공정 안에서 조건을 다시 확인합니다.", "반죽·성형·가열·포장 단계마다 제품 규격과 공정 조건의 연결을 살핍니다.", ShieldCheck],
  ["03", "RELEASE REVIEW", "다음 단계로 넘어갈 기준을 기록합니다.", "출고 전 제품 상태와 확인 항목을 검토하고, 실제 규격·라벨 기준을 최종 확인합니다.", PackageCheck],
  ["04", "STORAGE CONTEXT", "보관·조리 조건까지 함께 봅니다.", "현장 설비와 제품 라벨의 최신 기준을 바탕으로 보관·해동·조리 조건을 확인합니다.", Refrigerator],
] as const;

export default function QualitySafety() {
  return <SubPageLayout marker="02" eyebrow="QUALITY & SAFETY" breadcrumbLabel="품질·안전" heroVariant="manufacturing" heroImage="/manus-storage/real-quality-line-rnd-hq_04d19718.webp" heroImageAlt="제조 라인에서 제품 상태를 확인하는 바른푸드 현장" title={<>안전은 마지막 확인이 아니라,<br /><span className="text-[#9e3328]">공정 전체의 기준입니다.</span></>} description="제품의 사용 조건부터 공정·출고·보관 맥락까지 연결해, 확인이 필요한 항목을 다음 단계에서 다시 살핍니다.">
    <PageMeta title="품질·안전 | 바른푸드 제조 기준" description="바른푸드가 제품 사용 조건과 제조 공정, 출고·보관 기준을 연결해 확인하는 품질·안전 기록입니다." path="/manufacturing/quality" image="/manus-storage/barunfood-company-og-image_2bf6582a.jpg" imageAlt="바른푸드 품질·안전 — 공정 전체의 기준" />
    <FadeInSection className="bg-[#242321] px-5 py-20 text-white sm:px-8 sm:py-28 lg:px-12 lg:py-36"><div className="mx-auto max-w-[1440px]"><div className="grid gap-8 lg:grid-cols-[0.72fr_1.28fr] lg:items-end"><div><SectionEyebrow number="03" light>CHECKPOINT MAP</SectionEyebrow><p className="mt-8 max-w-sm text-sm leading-7 text-white/65">품질은 결과만 보는 일이 아니라, 제품이 만들어지고 사용되는 흐름 안에서 무엇을 다시 확인할지 정하는 일입니다.</p></div><h2 className="font-serif text-[clamp(2.4rem,4.6vw,5rem)] font-semibold leading-[1.03] tracking-[-0.08em]">확인 기준은,<br /><span className="text-[#f4bd75]">공정마다 이어집니다.</span></h2></div><div className="mt-14 grid border-y border-white/20 md:grid-cols-2 lg:mt-20 lg:grid-cols-4">{checkpoints.map(([number, label, title, text, Icon]) => <article key={label} className="border-b border-white/15 p-7 last:border-b-0 md:border-b-0 md:border-r md:even:border-r-0 lg:even:border-r lg:last:border-r-0"><div className="flex items-center justify-between"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#9e3328] text-[10px] font-bold">{number}</span><Icon className="h-5 w-5 text-[#f4bd75]" /></div><p className="mt-11 text-[10px] font-bold tracking-[0.16em] text-[#f4bd75]">{label}</p><h3 className="mt-3 text-lg font-bold tracking-[-0.04em]">{title}</h3><p className="mt-3 text-sm leading-6 text-white/60">{text}</p></article>)}</div></div></FadeInSection>
    <FadeInSection className="bg-[#f7f3eb] px-5 py-20 sm:px-8 sm:py-28 lg:px-12 lg:py-36"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[0.72fr_0.58fr_0.7fr]"><div><SectionEyebrow number="04">PUBLIC RECORD</SectionEyebrow><h2 className="mt-8 font-serif text-[clamp(2.3rem,4.4vw,4.7rem)] font-semibold leading-[1.04] tracking-[-0.08em]">공개 기록과<br />현재 확인을 구분합니다.</h2></div><div className="border-y border-[#d9d0c2] py-7 lg:border-l lg:border-y-0 lg:px-9"><p className="text-[10px] font-bold tracking-[0.16em] text-[#9e3328]">2016 / PUBLIC HISTORY</p><h3 className="mt-4 text-xl font-bold tracking-[-0.05em]">HACCP 인증 획득 기록</h3><p className="mt-4 text-sm leading-7 text-[#70685d]">공식 공개 연혁에는 2016년 HACCP 인증 획득 기록이 남아 있습니다. 적용 공정, 발급기관, 유효기간은 실제 증빙으로 별도 확인해야 합니다.</p></div><div className="rounded-bl-[72px] bg-[#ece5d9] p-8"><p className="text-[10px] font-bold tracking-[0.16em] text-[#9e3328]">REQUEST FILE</p><h3 className="mt-4 text-xl font-bold tracking-[-0.05em]">확인이 필요한 조건을 알려주세요.</h3><p className="mt-4 text-sm leading-7 text-[#70685d]">제품군, 사용 환경, 필요한 확인 항목을 남겨주시면 검토에 필요한 다음 정보를 안내합니다.</p><a href="/partnership#inquiry" className="consultation-cta mt-8 inline-flex items-center gap-2 border-b border-[#242321] pb-2 text-sm font-bold hover:border-[#9e3328] hover:text-[#9e3328]">품질·안전 기준 문의 <ArrowUpRight className="cta-arrow h-4 w-4" /></a></div></div></FadeInSection>
  </SubPageLayout>;
}
