import { ArrowUpRight, Beaker, FileSearch, FlaskConical, UtensilsCrossed } from "lucide-react";
import { FadeInSection } from "@/components/FadeInSection";
import { PageMeta } from "@/components/PageMeta";
import { SectionEyebrow } from "@/components/SectionEyebrow";
import { SubPageLayout } from "@/components/SubPageLayout";

const researchFlow = [
  ["01", "BRIEF", "메뉴와 현장 조건을 읽습니다.", "사용 장비, 조리 방식, 원하는 식감처럼 제품의 출발점을 정리합니다.", FileSearch],
  ["02", "PROTOTYPE", "도우와 제품의 방향을 테스트합니다.", "도우의 형태와 메뉴 적용을 검토하며, 제품군에 필요한 조건을 가설로 세웁니다.", FlaskConical],
  ["03", "APPLICATION", "조리 결과를 사용 맥락에서 봅니다.", "메뉴·설비·운영 흐름 안에서 제품이 어떻게 쓰이는지 함께 확인합니다.", UtensilsCrossed],
  ["04", "REVIEW", "다음 검토 항목을 남깁니다.", "확인 결과를 바탕으로 제품 규격과 다음 개선·개발 조건을 정리합니다.", Beaker],
] as const;

const publicHistory = [["2008", "도우 연구소 개설"], ["2015", "맞춤 도우 개발 기록"], ["2017", "화덕·흑미 라떼 도우 개발 기록"], ["2018", "피자 3종·플랫 피자 개발 기록"], ["2020", "도우·크로플 개발 및 특허 기록"]] as const;

export default function ResearchDevelopment() {
  return <SubPageLayout marker="02" eyebrow="RESEARCH & DEVELOPMENT" breadcrumbLabel="연구개발" heroVariant="manufacturing" heroImage="/assets/real-lab-rnd-hq.webp" heroImageAlt="연구 환경에서 샘플을 확인하는 바른푸드 현장" title={<>개발은 아이디어보다,<br /><span className="text-[#9e3328]">사용 조건에서 시작합니다.</span></>} description="메뉴의 의도와 현장 조건을 함께 읽고, 도우·제품의 방향을 테스트하며 다음 검토 항목을 기록합니다.">
    <PageMeta title="연구개발 | 바른푸드 제품 개발 기록" description="메뉴와 사용 환경을 출발점으로 도우·피자 제품의 방향과 다음 검토 항목을 설계하는 바른푸드 연구개발 기록입니다." path="/manufacturing/research" image="/manus-storage/barunfood-company-og-image_2bf6582a.jpg" imageAlt="바른푸드 연구개발 — 사용 조건에서 시작하는 개발" />
    <FadeInSection className="bg-[#ece5d9] px-5 py-20 sm:px-8 sm:py-28 lg:px-12 lg:py-36"><div className="mx-auto max-w-[1440px]"><div className="grid gap-10 lg:grid-cols-[0.76fr_1.24fr] lg:items-end"><div><SectionEyebrow number="03">DEVELOPMENT NOTE</SectionEyebrow><p className="mt-8 max-w-sm text-sm leading-7 text-[#70685d]">승인되지 않은 성과·수치·사례를 앞세우지 않고, 제품이 실제로 쓰이는 조건을 다음 테스트의 출발점으로 삼습니다.</p></div><h2 className="font-serif text-[clamp(2.45rem,4.6vw,5rem)] font-semibold leading-[1.03] tracking-[-0.08em]">한 번의 테스트가 아니라,<br /><span className="text-[#9e3328]">다음 판단을 위한 기록입니다.</span></h2></div><div className="mt-14 grid border-y border-[#cfc5b5] md:grid-cols-2 lg:mt-20 lg:grid-cols-4">{researchFlow.map(([number, label, title, text, Icon]) => <article key={label} className="border-b border-[#cfc5b5] p-7 last:border-b-0 md:border-b-0 md:border-r md:even:border-r-0 lg:even:border-r lg:last:border-r-0"><div className="flex items-center justify-between"><span className="text-[10px] font-bold tracking-[0.16em] text-[#9e3328]">{number} / {label}</span><Icon className="h-5 w-5 text-[#9e3328]" /></div><h3 className="mt-12 text-xl font-bold tracking-[-0.05em]">{title}</h3><p className="mt-3 text-sm leading-6 text-[#70685d]">{text}</p></article>)}</div></div></FadeInSection>
    <FadeInSection className="bg-[#242321] px-5 py-20 text-white sm:px-8 sm:py-28 lg:px-12 lg:py-36"><div className="mx-auto grid max-w-[1440px] gap-10 lg:grid-cols-[0.75fr_1.25fr]"><div><SectionEyebrow number="04" light>DOCUMENTED DEVELOPMENT</SectionEyebrow><h2 className="mt-8 font-serif text-[clamp(2.3rem,4.3vw,4.7rem)] font-semibold leading-[1.04] tracking-[-0.08em]">연구는 공개 가능한<br /><span className="text-[#f4bd75]">기록으로 이어집니다.</span></h2><div className="ingredient-window mt-10 h-48 overflow-hidden rounded-tr-[70px]"><img src="/manus-storage/real-dough-action_4e62c5cb.jpg" alt="도우의 상태를 손으로 확인하는 장면" className="h-full w-full object-cover" /></div></div><div className="border-t border-white/20">{publicHistory.map(([year, record], index) => <article key={year} className="grid gap-4 border-b border-white/20 py-7 sm:grid-cols-[90px_1fr_auto] sm:items-center"><span className="font-serif text-3xl font-semibold tracking-[-0.07em] text-[#f4bd75]">{year}</span><div><p className="text-[10px] font-bold tracking-[0.16em] text-white/45">PUBLIC HISTORY</p><h3 className="mt-2 text-lg font-bold tracking-[-0.04em]">{record}</h3></div><span className="text-[10px] font-bold tracking-[0.14em] text-white/45">FILE / {String(index + 1).padStart(2, "0")}</span></article>)}</div></div></FadeInSection>
    <FadeInSection className="bg-[#9e3328] px-5 py-16 text-white sm:px-8 lg:px-12 lg:py-20"><div className="mx-auto flex max-w-[1440px] flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><SectionEyebrow number="05" light>DEVELOPMENT INQUIRY</SectionEyebrow><h2 className="mt-7 font-serif text-[clamp(2.3rem,4.4vw,4.7rem)] font-semibold leading-[1.03] tracking-[-0.08em]">새 제품의 조건을<br />함께 검토할까요?</h2></div><a href="/partnership" className="consultation-cta inline-flex items-center justify-center gap-3 bg-white px-6 py-4 text-sm font-bold text-[#9e3328] hover:bg-[#242321] hover:text-white">제품 개발 문의 <ArrowUpRight className="cta-arrow h-4 w-4" /></a></div></FadeInSection>
  </SubPageLayout>;
}
